app:
  name: "user-management-system"
  version: "1.2.0"
  debug: true

server:
  host: "localhost"
  ports:
    - 3000
    - 3001
  ssl_enabled: false

features:
  - user_registration
  - email_notifications
